name: "Version mismatch"
description: "Version passt nicht? Log anhängen."
title: "Version mismatch: "
labels:
  - version-mismatch
body:
  - type: markdown
    attributes:
      value: |
        Schau in das Log und füge die Stelle mit dem Versionsfehler ein.
  - type: input
    id: stelle
    attributes:
      label: Wo tritt es auf?
      placeholder: z. B. Service oder Paketname.
  - type: textarea
    id: log
    attributes:
      label: Logstelle
      description: Kopiere die Zeilen mit dem Versionsproblem.
      render: shell
      placeholder: |
        [2024-05-01 10:15:03] Erwartet 1.4.0, gefunden 1.3.2
  - type: textarea
    id: kurz
    attributes:
      label: Kurzbeschreibung
      description: Was ist das Problem?
