// <auto-generated>
// This file is generated by scripts/update.ps1. Do not edit manually.
// </auto-generated>

namespace CSM.TmpeSync.Mod
{
    internal static class ModMetadata
    {
        /// <summary>
        /// Current version of the CSM TM:PE Sync mod. Update this value when publishing new builds.
        /// </summary>
        internal const string NewVersion = "0.1.0.0";

        /// <summary>
        /// Latest release tag for CSM TM:PE Sync.
        /// </summary>
        internal const string LatestCsmTmpeSyncReleaseTag = "v1.0.0.0";

        /// <summary>
        /// Legacy release tags for CSM TM:PE Sync (excluding the latest).
        /// </summary>
        internal static readonly string[] LegacyCsmTmpeSyncReleaseTags = new string[0];

        /// <summary>
        /// Latest release tag for Traffic Manager: President Edition.
        /// </summary>
        internal const string LatestTmpeReleaseTag = "11.9.3.0";

        /// <summary>
        /// Legacy release tags for Traffic Manager: President Edition (excluding the latest).
        /// </summary>
        internal static readonly string[] LegacyTmpeReleaseTags = new[]
        {
            "11.9.2.0",
            "11.9.1.0",
            "11.9.0.0",
            "11.8.0.0",
            "11.7.5.0",
            "11.7.4.0",
            "11.7.3.1",
            "11.7.3.0",
            "11.7.2.0",
            "11.7.1.2",
            "11.7.1.1",
            "11.7.1.1-test",
            "11.7.1.0-test",
            "11.7.0.1",
            "11.7.0.0",
            "11.6.6.3-stable",
            "11.6.6.3",
            "11.6.6.2",
            "11.6.6.1",
            "11.6.6.0",
            "11.6.5.3",
            "11.6.5.2-hotfix-1",
            "11.6.5.2",
            "11.6.5.1",
            "11.6.5.0",
            "11.6.4.8",
            "11.6.4.7",
            "11.6.4.6",
            "11.6.4.5",
            "11.6.4.4",
            "11.6.4.3",
            "11.6.4.2",
            "v11.6.4.1",
            "11.6.4",
            "11.6.3-test",
            "11.6.2-test",
            "11.6.1-test",
            "11.6.0-test",
            "11.5.2-hotfix2",
            "11.5.2-hotfix1",
            "11.5.2",
            "11.5.1-hotfix1",
            "11.5.1",
            "11.5.0",
            "11.4.0",
            "11.3.2",
            "11.3.1",
            "11.3.0",
            "11.2.3",
            "11.2.2",
            "11.2.1",
            "11.2.0",
            "11.1.2",
            "11.1.1-hotfix1",
            "11.1.1",
            "11.1.0",
            "11.0",
            "10.21.1",
            "10.21",
            "10.20",
            "10.19",
            "10.18",
            "10.17",
            "1.10.16",
            "1.10.15",
            "1.10.14",
        };

        /// <summary>
        /// Latest release tag for Cities: Skylines Multiplayer.
        /// </summary>
        internal const string LatestCsmReleaseTag = "v2309.286";

        /// <summary>
        /// Legacy release tags for Cities: Skylines Multiplayer (excluding the latest).
        /// </summary>
        internal static readonly string[] LegacyCsmReleaseTags = new[]
        {
            "v2305.270",
            "v2304.267",
            "v2211.229",
            "v2209.221",
            "v2209.211",
            "v2201.180",
            "v2104.134",
            "v2012.84",
            "v2008.44",
            "v2006.21",
            "v2005.13",
            "v2003.3",
            "1912.12",
        };

        /// <summary>
        /// Latest release tag for Cities Harmony.
        /// </summary>
        internal const string LatestCitiesHarmonyReleaseTag = "v2.2.2-0";

        /// <summary>
        /// Legacy release tags for Cities Harmony (excluding the latest).
        /// </summary>
        internal static readonly string[] LegacyCitiesHarmonyReleaseTags = new[]
        {
            "v2.2-1",
            "v2.2-0",
            "v2.0.4-2",
            "v2.0.4-1",
            "NExt2",
        };

    }
}

