// <auto-generated>
// This file is generated by scripts/manage_subtrees.py. Do not edit manually.
// </auto-generated>

namespace CSM.TmpeSync.Mod
{
    internal static class ModMetadata
    {
        /// <summary>
        /// Current version of the CSM TM:PE Sync mod. Update this value when publishing new builds.
        /// </summary>
        internal const string NewVersion = "0.1.0.0";

        /// <summary>
        /// Latest release tag for CSM TM:PE Sync.
        /// </summary>
        internal const string LatestCsmTmpeSyncReleaseTag = "v0.1.1";

        /// <summary>
        /// Latest release tag for Traffic Manager: President Edition.
        /// </summary>
        internal const string LatestTmpeReleaseTag = "11.9.3.0";

        /// <summary>
        /// Latest release tag for Cities: Skylines Multiplayer.
        /// </summary>
        internal const string LatestCsmReleaseTag = "v2309.286";

        /// <summary>
        /// Latest release tag for Cities Harmony.
        /// </summary>
        internal const string LatestCitiesHarmonyReleaseTag = "v2.2.2-0";

    }
}
